sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=bastianwiessner/rstats
    - REGISTRY_USER=$DOCKER_USERNAME
    - REGISTRY_PASS=$DOCKER_PASSWORD  

branches:
  only:
  - master

before_script:
  - docker pull "$IMAGE_NAME" || true

script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:v1"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:v1"
  on:
    branch: master

